/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_tom_HelloJNI */

#ifndef _Included_cn_tom_HelloJNI
#define _Included_cn_tom_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_tom_HelloJNI
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_tom_HelloJNI_get
  (JNIEnv *, jclass);

/*
 * Class:     cn_tom_HelloJNI
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_tom_HelloJNI_set
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
